name: lookfy
description: Consultor de estilo masculino. Gera looks personalizados para cada ocasião.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.4.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_secure_storage: ^9.0.0
  image_picker: ^1.0.8
  camera: ^0.10.5+2
  share_plus: ^7.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.0
  build_runner: ^2.4.6

flutter:
  uses-material-design: true
  assets:
    - assets/catalog/
    
flutter:
  uses-material-design: true
  assets:
    - assets/catalog/
